/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123918-gf7ca6f7481-20260411"
#endif /* AVUTIL_FFVERSION_H */
